// Niantic-style data schema + sample data
// Generated by GitHub Copilot assistant for jkgb92-png/The-real-earth

export type NianticPOIType = 'pokestop' | 'gym' | 'portal' | 'event' | 'poi' | string;

export interface NianticData {
  id: string;                     // unique identifier
  name: string;                   // display name
  description?: string;           // optional description
  type: NianticPOIType;           // POI type
  location: {
    lat: number;
    lng: number;
    alt?: number;
  };
  tags?: string[];                // e.g., ["historic", "art"]
  properties?: Record<string, any>; // arbitrary provider-specific fields
  updatedAt?: string;             // ISO timestamp
}

// Example sample data
export const nianticData: NianticData[] = [
  {
    id: "niantic-0001",
    name: "Old Town Fountain",
    description: "A historic fountain popular with visitors.",
    type: "pokestop",
    location: { lat: 37.7749, lng: -122.4194 },
    tags: ["historic", "water-feature"],
    properties: {
      verified: true,
      photos: 3
    },
    updatedAt: new Date().toISOString()
  },
  {
    id: "niantic-0002",
    name: "Riverside Gym",
    description: "Friendly community gym with weekly events.",
    type: "gym",
    location: { lat: 37.7765, lng: -122.4172 },
    tags: ["gym", "events"],
    properties: {
      eventSchedule: [
        { name: "Raid Sunday", day: "sunday", time: "10:00" }
      ]
    },
    updatedAt: new Date().toISOString()
  }
];

// Helper: convert NianticData -> GeoJSON Feature
export function toGeoJSONFeature(item: NianticData) {
  return {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [item.location.lng, item.location.lat]
    },
    properties: {
      id: item.id,
      name: item.name,
      description: item.description,
      type: item.type,
      tags: item.tags,
      ...item.properties,
      updatedAt: item.updatedAt
    }
  };
}

// Helper: FeatureCollection
export function toFeatureCollection(items: NianticData[]) {
  return {
    type: "FeatureCollection",
    features: items.map(toGeoJSONFeature)
  };
}

export default nianticData;
